name: Build and Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pyyaml

    - name: Build executable
      run: pyinstaller --onefile --noconsole src/project.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: exe-file
        path: dist/project.exe
